[build]
  functions = "netlify/functions"
  # custom build command that install bun and run build
  command = "./scripts/build.sh"
[build.environment]
   # disable NPM install
   NPM_FLAGS = "--version"
  
[serve]
  command = "./scripts/serve.sh"